### ISSUE TITLE
Disable "require-await" rule

### ISSUE THREAD

**Issue by Turbo87** [simplabs/eslint-config-simplabs#33]
I don't think this rule makes sense anymore. Even if all a function does is return the result of another async function it should be allowed to mark the function as `async` to clearly communicate that this function is supposed to be async.

@marcoow @pangratz @jessica-jordan opinions?

**Comment by jayjayjpg** [comment]
As far as I understand, `async` functions may, but don't need to contain an`await` expression specificationwise, so I'd agree that the rule can be omitted to better highlight any asynchronous operations regardless of the existence of `await` in their function bodies.

**Comment by marcoow** [comment]
Yeah, seems fine to disable this.
