### ISSUE TITLE
Enable "comma-dangle" rule

### ISSUE THREAD

**Issue by Turbo87** [simplabs/eslint-config-simplabs#40]
I would like to enable the ESLint `comma-dangle` rule using the `always-multiline` configuration (see http://eslint.org/docs/rules/comma-dangle#always-multiline).

To prevent this from becoming a huge bike shedding discussion I would like to focus on the pros and cons of trailing commas. Feel free to complete the list in the comments.

from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas:

> Trailing commas (sometimes called "final commas") can be useful when adding new elements, parameters, or properties to JavaScript code. If you want to add a new property, you can simply add a new line without modifying the previously last line if that line already uses a trailing comma. This makes version-control diffs cleaner and editing code might be less troublesome.
>
> JavaScript has allowed trailing commas in array literals since the beginning, and later added them to object literals (ECMAScript 5) and most recently (ECMAScript 2017) to function parameters.
>
> JSON, however, disallows trailing commas.

### Pro

- less work when adding new items to a list or object
- easier to read version control diffs

### Con

- not supported in old browser (irrelevant thanks to Babel)
- not supported in JSON (ESLint doesn't work in JSON, and single quotes don't work there either but we still use them)

**Comment by pangratz** [comment]
I don't have a strong opinion in favor or against this rule. I can definitely see the pro's, though I think it's not that big of an issue regarding interpretability of the diff. But enabling the rule would be ok for me.

I abstain from voting, though I think we should enforce either one, as having `ignore` is confusing since both ways are allowed.

**Comment by jayjayjpg** [comment]
No strong opinion from my side either and agreeing with @pangratz, that setting it soon is better than staying ambiguous on that rule. I'd be for trailing commas if this means that we can write this one down

**Comment by Turbo87** [comment]
FWIW https://github.com/ember-cli/ember-cli/blob/master/.eslintrc.js#L61

**Comment by marcoow** [comment]
I don't like it, mostly for aesthetic reasons.

> This makes version-control diffs cleaner and editing code might be less troublesome.

While this sounds like it makes sense I have never seen any of the 2 problems occur in reality. I certainly never have been troubled by having to add a comma when adding a new element to a list ;)

Obviously this is a topic that people tend to have strong feelings about like everyone used to have about tabs vs. spaces (maybe there are communities where the debate is still ongoing even) and I have no interest in getting into a long discussion about a detail that doesn't really matter much anyway. So if it's a majority decision to add it let's add it.

Another reason I don't like this though is that the concept of _"If in the future I might ever do x then if I do y now that will make things easier"_ generally leads to a lot of bad things in software engineering (I'm aware that saying this in this context is as much an exaggeration as using the word _"troublesome"_ in the Mozilla docs quoted above 😉).

**Comment by Turbo87** [comment]
> While this sounds like it makes sense I have never seen any of the 2 problems occur in reality

they do occur daily, but apparently you're not quite as annoyed by them as others 😉 

> So if it's a majority decision to add it let's add it.

👍
